### ISSUE TITLE
✅[Feat] 로그인 정보 기반 페이지 이동 경로 지정 및 데이터 전달 로직 구현

### ISSUE THREAD

**Issue by ewinkite** [toy-1/wiki#21]
## Description
로그인시 로컬스토리지에 UID 저장하고 이를 기반으로 로그인 유/무 확인하여 페이지 리다이렉트시킬 예정입니다. 이 때 UID 기반으로 ID(이메일)값 내려주어 헤더/위키 등에서 활용할 수 있도록 로직 구현하려고 합니다.

## Todo
- [x] 로그인시 로컬스토리지에 UID 저장하는 로직 구현
- [x] 로컬스토리지에 UID 있으면 입력한 주소로 이동, 없으면 로그인페이지로 이동될 수 있도록 경로 설정
- [x] UID 기반으로 ID(이메일)값 내려주는 로직 구현
